group:
  - repos:
      - chipsalliance/fpga-interchange-schema
      - chipsalliance/f4pga-examples
      - chipsalliance/fpga-tool-perf
      - chipsalliance/fasm
      - chipsalliance/f4pga-bitstream-viewer
    files:
      - CODE_OF_CONDUCT.md
      - CONTRIBUTING.md
