name: Sync Files
on:
  push:
    branches:
      - main
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Repo File Sync
        uses: BetaHuhn/repo-file-sync-action@v1.16.0
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          COMMIT_BODY: "Signed-off-by: common-config-bot <common.config.bot@gmail.com>"
          FORK: common-config-bot
          GIT_USERNAME: common-config-bot
          GIT_EMAIL: common.config.bot@gmail.com
